name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/702846291559/locations/global/workloadIdentityPools/github/providers/github-actions
          service_account: gha-deployer@cutrush-ai.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      # ⬇️ your build/deploy commands (examples)
      - run: gcloud run deploy cutrush-render --source . --region us-central1 --allow-unauthenticated
